(function(){
 'use strict';
 const H=window.StageMusicHarmonic;
 const fmt=iso=>{if(!iso)return'—';const d=new Date(iso);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(d)};
 const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const detect=text=>{const chords=H.extractChords(text);const sections=String(text||'').split(/\r?\n/).map(H.sectionName).filter(Boolean);return{chords,sections}};
 const formatChordPro=text=>String(text||'').replace(/\r/g,'').split('\n').map(line=>{const section=H.sectionName(line);if(section)return`[${section}]`;if(H.isChordLine(line))return String(line).replace(/\S+/g,token=>H.parseChordToken(token)?token:'').trim().replace(/\s+/g,'  ');return line.replace(/\s+$/,'')}).join('\n').replace(/\n{3,}/g,'\n\n').trim();
 document.addEventListener('DOMContentLoaded',async()=>{if(!document.body.matches('[data-page="inserir-cifra"]'))return;if(!await window.StageMusicAuth?.ensureAuthenticated?.('inserir-cifra.html'))return;
  if(!H){console.error('Motor harmônico não carregado.');return;}
  const $=id=>document.getElementById(id),fields={id:$('song-id'),title:$('song-title'),artist:$('song-artist'),style:$('song-style'),key:$('song-key'),bpm:$('song-bpm'),tags:$('song-tags'),notes:$('song-notes'),content:$('song-content'),capo:$('song-capo')};
  const preview=$('song-preview'),form=$('song-form'),library=$('local-library'),toast=$('editor-toast'),acc=$('accidental-mode');let timer=null,history=[],historyPos=-1,recording=true;
  try{acc.value=localStorage.getItem('stage_music_accidental_mode')||'preserve'}catch{}
  const payload=()=>({id:fields.id.value,title:fields.title.value,artist:fields.artist.value,style:fields.style?.value||'',key:fields.key.value,bpm:fields.bpm.value,tags:fields.tags.value,notes:fields.notes.value,content:fields.content.value,capo:Number(fields.capo?.value||0)});
  const say=m=>{toast.textContent=m;toast.classList.add('visible');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('visible'),2400)};
  const snapshot=()=>JSON.stringify(payload());
  const pushHistory=()=>{if(!recording)return;const s=snapshot();if(history[historyPos]===s)return;history=history.slice(0,historyPos+1);history.push(s);if(history.length>60)history.shift();historyPos=history.length-1;renderInsights()};
  const applySnapshot=s=>{recording=false;load(JSON.parse(s));recording=true;render()};
  const renderInsights=()=>{const d=detect(fields.content.value);$('chord-count').textContent=`${d.chords.length} acordes detectados`;$('section-count').textContent=`${d.sections.length} seções`;$('history-count').textContent=`Histórico ${historyPos+1}/${history.length}`};
  const render=()=>{preview.textContent=`${fields.title.value||'Sem título'}\n${fields.artist.value||'Sem artista'}${fields.style?.value?` • ${fields.style.value}`:''} • Tom ${fields.key.value} • ${fields.bpm.value||'--'} BPM${Number(fields.capo?.value||0)?` • Capo ${fields.capo.value}`:''}\n${fields.tags.value?`Tags: ${fields.tags.value}\n`:''}\n${fields.content.value||'Preencha a cifra para visualizar aqui.'}`;renderInsights()};
  const stats=()=>{const x=window.StageMusicLocalDB.getStats();$('stats-songs').textContent=x.songsCount;$('stats-draft').textContent=x.draftExists?`Rascunho em ${fmt(x.lastDraftUpdatedAt)}`:'Nenhum rascunho';$('draft-stamp').textContent=x.lastDraftUpdatedAt?`Rascunho salvo automaticamente em ${fmt(x.lastDraftUpdatedAt)}`:'Auto-save pronto';$('save-stamp').textContent=x.lastSongUpdatedAt?`Última cifra salva em ${fmt(x.lastSongUpdatedAt)}`:'Nenhuma cifra local salva'};
  const ensureKeyOption=value=>{if(!value||[...fields.key.options].some(option=>option.value===value))return;const option=document.createElement('option');option.value=value;option.textContent=value;fields.key.appendChild(option)};
  const load=s=>{fields.id.value=s?.id||'';fields.title.value=s?.title||'';fields.artist.value=s?.artist||'';if(fields.style)fields.style.value=s?.style||'';ensureKeyOption(s?.key);fields.key.value=s?.key||'C';fields.bpm.value=s?.bpm||72;fields.tags.value=Array.isArray(s?.tags)?s.tags.join(', '):(s?.tags||'');fields.notes.value=s?.notes||'';fields.content.value=s?.content||'';if(fields.capo)fields.capo.value=String(s?.capo||0);render()};
  const drawLib=()=>{const songs=window.StageMusicLocalDB.getAllSongs();library.innerHTML=songs.length?songs.map(s=>`<article class="library-item"><div><strong>${esc(s.title)}</strong><small>${esc(s.artist)} • Tom ${esc(s.key)} • ${esc(s.bpm)} BPM${s.capo?` • Capo ${s.capo}`:''}</small><small>Atualizada em ${esc(fmt(s.updatedAt))}</small></div><div class="library-actions"><button class="btn btn-outline btn-mini" data-open-song="${esc(s.id)}">Abrir</button><button class="btn btn-ghost btn-mini" data-delete-song="${esc(s.id)}">Excluir</button></div></article>`).join(''):'<article class="library-empty"><strong>Nenhuma cifra local ainda</strong><small>Crie sua primeira cifra inteligente.</small></article>';stats()};
  const saveDraft=feedback=>{const p=payload();if(!p.title&&!p.artist&&!p.content){window.StageMusicLocalDB.clearDraft();stats();return}window.StageMusicLocalDB.saveDraft(p);stats();if(feedback)say('Rascunho protegido salvo.')};
  const schedule=()=>{clearTimeout(timer);timer=setTimeout(()=>saveDraft(false),450)};
  form.addEventListener('submit',async e=>{e.preventDefault();const s=window.StageMusicLocalDB.saveSong(payload());fields.id.value=s.id;drawLib();render();say('Cifra salva com o tom completo e pronta para o Live.');if(window.StageMusicCloudSync?.syncSong){try{await window.StageMusicCloudSync.syncSong(s)}catch(error){console.warn('Sync opcional não executado:',error?.message||error)}}});
  Object.values(fields).filter(Boolean).forEach(f=>{f.addEventListener('input',()=>{render();schedule();clearTimeout(pushHistory.t);pushHistory.t=setTimeout(pushHistory,250)});f.addEventListener('change',()=>{render();schedule();pushHistory()})});
  acc.addEventListener('change',()=>{try{localStorage.setItem('stage_music_accidental_mode',acc.value)}catch{};say(acc.value==='preserve'?'A escrita original será preservada.':acc.value==='flat'?'Transposição preferirá bemóis.':'Transposição preferirá sustenidos.')});
  $('transpose-down').onclick=()=>transpose(-1);$('transpose-up').onclick=()=>transpose(1);
  function transpose(step){const originalKey=fields.key.value||'C';fields.content.value=H.transposeText(fields.content.value,step,acc.value,originalKey);fields.key.value=H.transposeKey(originalKey,step,acc.value);render();pushHistory();saveDraft(false);say(`Transposição ${step>0?'+1':'−1'} aplicada em ${fields.key.value}.`)}
  $('detect-key').onclick=()=>{const k=H.detectKey(fields.content.value);if(!k)return say('Não foi possível detectar acordes suficientes.');ensureKeyOption(k);fields.key.value=k;render();pushHistory();say(`Tom provável detectado: ${k}.`)};
  $('format-chords').onclick=()=>{fields.content.value=formatChordPro(fields.content.value);render();pushHistory();saveDraft(false);say('Cifra formatada por seções e acordes.')};
  $('section-palette').addEventListener('click',e=>{const n=e.target.dataset.section;if(!n)return;const t=fields.content,start=t.selectionStart,end=t.selectionEnd,insert=`${start&&t.value[start-1]!='\n'?'\n':''}[${n}]\n`;t.setRangeText(insert,start,end,'end');t.focus();render();pushHistory();schedule()});
  $('undo-edit').onclick=()=>{if(historyPos<=0)return say('Não há alteração anterior.');historyPos--;applySnapshot(history[historyPos]);say('Alteração desfeita.')};
  $('redo-edit').onclick=()=>{if(historyPos>=history.length-1)return say('Não há alteração posterior.');historyPos++;applySnapshot(history[historyPos]);say('Alteração refeita.')};
  library.addEventListener('click',e=>{const id=e.target.dataset.openSong,del=e.target.dataset.deleteSong;if(id){const s=window.StageMusicLocalDB.getSongById(id);if(s){load(s);pushHistory();say('Cifra carregada no editor.')}}if(del){const s=window.StageMusicLocalDB.getSongById(del);if(confirm(`Excluir "${s?.title||'Sem título'}"?`)){window.StageMusicLocalDB.deleteSong(del);drawLib();say('Cifra removida.')}}});
  $('load-demo').onclick=()=>{load({title:'Santo',artist:'Ariane Mazur',key:'Bbm',bpm:74,capo:1,tags:['worship','palco'],notes:'Subir dinâmica no refrão final.',content:'[Intro]\nBbm  Gb  Db  Ab\n\n[Verso]\nBbm              Gb\nTeu nome é santo sobre mim\nDb               Ab\nTua presença enche este lugar\n\n[Refrão]\nBbm      Gb\nSanto, santo\nDb           Ab\nÉs digno de louvor'});pushHistory();saveDraft(true)};
  $('save-draft').onclick=()=>saveDraft(true);
  const clearEditor=({confirmUser=true,message='Editor limpo.'}={})=>{if(confirmUser&&!confirm('Limpar editor e rascunho?'))return false;form.reset();fields.id.value='';fields.key.value='C';fields.bpm.value='72';if(fields.capo)fields.capo.value='0';acc.value='preserve';window.StageMusicLocalDB.clearDraft();history=[];historyPos=-1;render();pushHistory();drawLib();window.dispatchEvent(new CustomEvent('stage-music-editor-cleared'));if(message)say(message);return true};
  $('clear-editor').onclick=()=>clearEditor();
  window.StageMusicEditor={payload,load,clear:opts=>clearEditor(Object.assign({confirmUser:false},opts||{})),render,say};
  $('export-local-json').onclick=()=>{const blob=new Blob([window.StageMusicLocalDB.exportSongs()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`stage-music-cifras-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);say('Backup JSON exportado.')};
  const draft=window.StageMusicLocalDB.getDraft();if(draft)load(draft);render();pushHistory();drawLib();
 });
})();
