(function(){
'use strict';
const $=id=>document.getElementById(id),PROFILE_KEY='stage_music_live_profile';
const normalize=value=>String(value||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').replace(/^(.{4})(.+)$/,'$1-$2').slice(0,9);
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
function toast(message){const el=$('invite-toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
let selected={role:'vocal',instrument:'Vocal',view:'lyrics'};
function applyRole(button){document.querySelectorAll('.invite-role-card').forEach(item=>item.classList.toggle('active',item===button));selected={role:button.dataset.role||'vocal',instrument:button.dataset.instrument||'Vocal',view:button.dataset.view||'lyrics'};if($('invite-instrument'))$('invite-instrument').value=selected.instrument;const helper=$('invite-helper');if(helper){helper.textContent=selected.view==='lyrics'?'Você entrará em letra limpa para cantar.':selected.view==='director'?'Você será direcionado para criar ou controlar a Sala Live.':'Você entrará em cifra completa com acordes.'}}
function openRoom(){const code=normalize($('invite-room-code')?.value||''),name=String($('invite-display-name')?.value||'').trim(),instrument=$('invite-instrument')?.value||selected.instrument,view=selected.role==='diretor'?'director':(selected.view||'chords');if(!code&&selected.role!=='diretor')return toast('Digite o código da Sala Live.');write(PROFILE_KEY,{name:name||read(PROFILE_KEY,{}).name||'Convidado',instrument,viewMode:view,inviteRole:selected.role,updatedAt:new Date().toISOString()});sessionStorage.setItem('stage_music_invite_profile',JSON.stringify({name,instrument,viewMode:view,role:selected.role,code}));if(selected.role==='diretor'){location.href='sala-live.html?director=1';return}location.href=`sala-live.html?room=${encodeURIComponent(code)}&role=${encodeURIComponent(selected.role)}&instrument=${encodeURIComponent(instrument)}&view=${encodeURIComponent(view)}`}
document.addEventListener('DOMContentLoaded',()=>{const params=new URLSearchParams(location.search),code=params.get('room')||params.get('code')||'';if(code&&$('invite-room-code'))$('invite-room-code').value=normalize(code);const stored=read(PROFILE_KEY,{});if(stored.name&&$('invite-display-name'))$('invite-display-name').value=stored.name;if(stored.instrument&&$('invite-instrument'))$('invite-instrument').value=stored.instrument;document.querySelectorAll('.invite-role-card').forEach(btn=>btn.addEventListener('click',()=>applyRole(btn)));$('invite-instrument')?.addEventListener('change',event=>{selected.instrument=event.target.value;if(/vocal|back|voz|cantor/i.test(selected.instrument)){selected.role='vocal';selected.view='lyrics'}else if(/direção|diretor/i.test(selected.instrument)){selected.role='diretor';selected.view='director'}else{selected.role=selected.role==='diretor'?'musico':selected.role;selected.view=selected.role==='vocal'?'lyrics':'chords'}});$('invite-room-code')?.addEventListener('input',event=>{const value=normalize(event.target.value);event.target.value=value});$('invite-open-room')?.addEventListener('click',openRoom)});
})();
