(function(){
  'use strict';
  const ROOMS_KEY='stage_music_live_rooms_v1',CURRENT_KEY='stage_music_current_room',PROFILE_KEY='stage_music_live_profile';
  const channel='BroadcastChannel' in window?new BroadcastChannel('stage-music-live-room'):null;
  const safe=(value,fallback)=>{try{return JSON.parse(value)??fallback}catch{return fallback}};
  const read=(key,fallback)=>window.StageMusicSafeStorage?.get?.(key,fallback)??safe(localStorage.getItem(key),fallback);
  const write=(key,value)=>window.StageMusicSafeStorage?.set?.(key,value)??(localStorage.setItem(key,JSON.stringify(value)),true);
  const toast=message=>window.StageMusicToast?.(message);
  function ctx(){const current=read(CURRENT_KEY,null),rooms=read(ROOMS_KEY,{});return current?.code?{current,rooms,room:rooms[current.code]||null}:null}
  function choiceKey(code){return `stage_music_reader_choice_${String(code||'').toUpperCase()}`}
  function isDirector(c){return !!(c?.room&&c.current?.role==='director'&&c.room.directorId===c.current.memberId)}
  function member(c){return c?.room?.members?.find(m=>m.id===c.current?.memberId)||null}
  function saveRoom(c){if(!c?.room||!c.current?.code)return; c.rooms[c.current.code]=c.room; write(ROOMS_KEY,c.rooms); channel?.postMessage({type:'rooms-updated',source:'live-choice',at:new Date().toISOString()}); if(window.StageMusicFirebaseLive?.isReady?.()&&window.StageMusicAuth?.getState?.().mode==='online'){(window.StageMusicLiveStability?.safePutRoom?.(c.room,{source:'live-choice'})||window.StageMusicFirebaseLive.putRoom(c.room)).catch(error=>console.warn('Visualização letra/cifra:',error?.message||error));}}
  function applyChoice(mode,{persist=true,notify=true}={}){mode=mode==='lyrics'?'lyrics':'chords'; const c=ctx(); window.StageMusicLiveMode?.setDisplayMode?.(mode); if(mode==='lyrics')window.StageMusicLiveMode?.setReadingProfile?.('vocal'); else window.StageMusicLiveMode?.setReadingProfile?.('musician'); if(c?.room&&!isDirector(c)){const m=member(c); if(m){m.viewMode=mode;m.updatedAt=new Date().toISOString();c.room.updatedAt=new Date().toISOString();saveRoom(c)}} if(c?.current?.code){try{localStorage.setItem(choiceKey(c.current.code),mode);localStorage.setItem('stage_music_live_view_preference',mode)}catch{}} const profile=read(PROFILE_KEY,{}); write(PROFILE_KEY,{...profile,viewMode:mode,updatedAt:new Date().toISOString()}); hidePrompt(); if(notify)toast?.(mode==='lyrics'?'Letra limpa ativada.':'Cifra completa ativada.');}
  function ensurePrompt(){let el=document.getElementById('live-view-choice'); if(el)return el; el=document.createElement('section'); el.id='live-view-choice'; el.className='live-view-choice'; el.hidden=true; el.innerHTML='<div><span class="eyebrow">ESCOLHA SUA LEITURA</span><strong>Você quer ver letra ou cifra?</strong><small>Vocalistas: letra limpa. Músicos: cifra com acordes. Você pode trocar depois em “Ver letra / Ver cifra”.</small></div><div class="live-view-choice-actions"><button type="button" data-live-choice="lyrics">Quero letra</button><button type="button" data-live-choice="chords">Quero cifra</button></div>'; const head=document.getElementById('live-song-head'); head?.after(el); el.addEventListener('click',event=>{const b=event.target.closest('[data-live-choice]'); if(b)applyChoice(b.dataset.liveChoice)}); return el;}
  function hidePrompt(){const el=document.getElementById('live-view-choice'); if(el)el.hidden=true; document.body.classList.remove('live-choice-pending')}
  function sync(){const c=ctx(); if(!c?.room||c.room.status!=='active'||isDirector(c)){hidePrompt();return} const key=choiceKey(c.current.code),stored=localStorage.getItem(key); if(stored==='lyrics'||stored==='chords'){window.StageMusicLiveMode?.setDisplayMode?.(stored); return} const m=member(c); if(m?.viewMode==='lyrics'||m?.viewMode==='chords'){try{localStorage.setItem(key,m.viewMode)}catch{};window.StageMusicLiveMode?.setDisplayMode?.(m.viewMode);return} const el=ensurePrompt(); el.hidden=false; document.body.classList.add('live-choice-pending')}
  document.addEventListener('DOMContentLoaded',()=>{if(!document.body.matches('[data-page="modo-live"]'))return; sync(); setInterval(sync,1500); window.addEventListener('storage',e=>{if([ROOMS_KEY,CURRENT_KEY].includes(e.key))setTimeout(sync,40)}); channel?.addEventListener('message',()=>setTimeout(sync,40)); window.addEventListener('stage:live-song-changed',()=>setTimeout(sync,120)); document.getElementById('live-view-toggle')?.addEventListener('click',()=>setTimeout(()=>{const mode=window.StageMusicLiveMode?.getDisplayMode?.()==='lyrics'?'lyrics':'chords';applyChoice(mode,{notify:false})},40));});
  window.StageMusicLiveChoice={applyChoice,sync};
})();
