(function(){
'use strict';
const ROOMS_KEY='stage_music_live_rooms_v1',CURRENT_KEY='stage_music_current_room',SETLIST_KEY='stage_music_setlists_v1',TEAMS_KEY='stage_music_teams_v1',ACTIVE='stage_music_active_setlist';
const $=id=>document.getElementById(id),now=()=>new Date().toISOString();
const safeParse=(v,f)=>{try{return JSON.parse(v)??f}catch{return f}};
const read=(k,f)=>window.StageMusicSafeStorage?.get?.(k,f)??safeParse(localStorage.getItem(k),f);
const write=(k,v)=>window.StageMusicSafeStorage?.set?.(k,v)??(localStorage.setItem(k,JSON.stringify(v)),true);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const code=()=>`LIVE-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const memberId=()=>`member_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;
const channel='BroadcastChannel'in window?new BroadcastChannel('stage-music-live-room'):null;
let rooms=read(ROOMS_KEY,{}),current=read(CURRENT_KEY,null),heartbeat=null;
const toast=t=>{const e=$('room-toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)};
const saveRooms=()=>{write(ROOMS_KEY,rooms);channel?.postMessage({type:'rooms-updated',at:now()});render()};
const getSetlists=()=>{const x=read(SETLIST_KEY,[]);return Array.isArray(x)?x:[]};
const getTeams=()=>{const x=read(TEAMS_KEY,[]);return Array.isArray(x)?x:[]};
const room=()=>current?.code?rooms[current.code]||null:null;
const activeMember=()=>room()?.members?.find(m=>m.id===current?.memberId)||null;
const modeLabels={normal:'Normal',repeat:'Repetir seção',vamp:'Vamp contínuo',ministry:'Ministração',spontaneous:'Espontâneo',ending:'Preparar final'};
const dynamicsLabels={normal:'Normal',soft:'Suave',build:'Crescendo',full:'Banda completa',drop:'Corte / somente voz'};
function defaultFlow(){return{section:'',mode:'normal',dynamics:'normal',modulation:0,cue:'',updatedAt:'',history:[]}}
function normalizeRoom(r){return{id:r.id||`room_${Date.now()}`,code:r.code||code(),name:r.name||'Sala Live',setlistId:r.setlistId||'',teamId:r.teamId||'',directorId:r.directorId||'',index:Number(r.index)||0,command:r.command||'',commandAt:r.commandAt||'',flow:Object.assign(defaultFlow(),r.flow||{}),status:r.status||'active',createdAt:r.createdAt||now(),updatedAt:r.updatedAt||now(),members:Array.isArray(r.members)?r.members:[]}}
Object.keys(rooms).forEach(k=>rooms[k]=normalizeRoom(rooms[k]));
function currentSetlist(r=room()){return getSetlists().find(x=>x.id===r?.setlistId)||null}
function currentSong(r=room()){const list=currentSetlist(r);return list?.songs?.[r?.index||0]||null}
function extractSections(song){const text=String(song?.content||'');const found=[];text.split('\n').forEach(line=>{const m=line.trim().match(/^\[([^\]]+)\]$|^(Intro|Verso(?:\s*\d+)?|Pré-Refrão|Pre-Refrão|Refrão|Refrao|Ponte|Solo|Interlúdio|Interludio|Ministração|Ministracao|Final)\s*:?$/i);const name=(m?.[1]||m?.[2]||'').trim();if(name&&!found.some(x=>x.toLowerCase()===name.toLowerCase()))found.push(name)});return found}
function setCurrentRoom(codeValue,memberIdValue,role){current={code:codeValue,memberId:memberIdValue,role};write(CURRENT_KEY,current);startHeartbeat();render()}
function clearCurrent(){current=null;write(CURRENT_KEY,null);clearInterval(heartbeat);heartbeat=null;render()}
function startHeartbeat(){clearInterval(heartbeat);if(!current)return;heartbeat=setInterval(()=>{const r=room(),m=activeMember();if(!r||!m)return;m.lastSeenAt=now();r.updatedAt=now();write(ROOMS_KEY,rooms);channel?.postMessage({type:'heartbeat',code:r.code})},8000)}
function createRoom(){const setlistId=$('room-setlist-select').value,name=$('room-display-name').value.trim()||'Diretor musical';if(!setlistId)return toast('Crie ou selecione um repertório primeiro.');const c=code(),mid=memberId(),list=getSetlists().find(x=>x.id===setlistId);const r=normalizeRoom({code:c,name:`${list?.name||'Repertório'} • Sala Live`,setlistId,teamId:$('room-team-select').value,directorId:mid,members:[{id:mid,name,instrument:$('room-instrument').value,role:'director',joinedAt:now(),lastSeenAt:now()}]});rooms[c]=r;write(ACTIVE,{...list,startedAt:now()});setCurrentRoom(c,mid,'director');saveRooms();toast('Sala Live criada.')}
function joinRoom(){const c=$('join-room-code').value.trim().toUpperCase(),r=rooms[c];if(!r||r.status!=='active')return toast('Sala não encontrada neste dispositivo.');const mid=memberId(),name=$('room-display-name').value.trim()||'Músico';r.members.push({id:mid,name,instrument:$('room-instrument').value,role:'member',joinedAt:now(),lastSeenAt:now()});r.updatedAt=now();setCurrentRoom(c,mid,'member');const list=currentSetlist(r);if(list)write(ACTIVE,{...list,startedAt:now()});saveRooms();toast('Você entrou na Sala Live.')}
function leaveRoom(){const r=room();if(r&&current){r.members=(r.members||[]).filter(m=>m.id!==current.memberId);r.updatedAt=now();if(current.role==='director')r.status='ended';saveRooms()}clearCurrent();toast('Você saiu da sala.')}
function endRoom(){const r=room();if(!r)return;r.status='ended';r.updatedAt=now();saveRooms();clearCurrent();toast('Sala encerrada.')}
function move(step){const r=room(),list=currentSetlist(r);if(!r||!list)return;const next=Math.max(0,Math.min((list.songs?.length||1)-1,r.index+step));if(next===r.index)return toast(step<0?'Início do repertório':'Fim do repertório');r.index=next;r.command='';r.commandAt='';r.flow=defaultFlow();r.updatedAt=now();write(ACTIVE,{...list,startedAt:now()});saveRooms();window.dispatchEvent(new CustomEvent('stage-room-position',{detail:{index:next,room:r}}))}
function sendCommand(text){const r=room();if(!r||!String(text||'').trim())return;r.command=String(text).trim();r.commandAt=now();r.updatedAt=now();saveRooms();if($('director-message'))$('director-message').value='';toast('Aviso enviado aos músicos.')}
function pushFlowHistory(r,label){const item={id:`flow_${Date.now()}`,label,at:now()};r.flow.history=[item,...(r.flow.history||[])].slice(0,12)}
function applyFlow(patch,label){const r=room();if(!r||current?.role!=='director')return toast('Somente o diretor pode alterar o Worship Flow.');r.flow=Object.assign(defaultFlow(),r.flow||{},patch||{}, {updatedAt:now()});pushFlowHistory(r,label||'Fluxo atualizado');r.command=label||'Fluxo atualizado';r.commandAt=now();r.updatedAt=now();saveRooms();toast(label||'Worship Flow atualizado.')}
function flowFromControls(){return{section:$('flow-section-select')?.value||'',dynamics:$('flow-dynamics')?.value||'normal',modulation:Number($('flow-modulation')?.value||0),mode:$('flow-mode')?.value||'normal'}}
function handleFlowAction(action){const base=flowFromControls();if(action==='apply')return applyFlow(base,'Fluxo musical atualizado');if(action==='repeat')return applyFlow({...base,mode:'repeat'},`Repetir ${base.section||'seção atual'}`);if(action==='vamp')return applyFlow({...base,mode:'vamp'},`Vamp contínuo em ${base.section||'seção atual'}`);if(action==='ministry')return applyFlow({...base,mode:'ministry',dynamics:'soft'},'Entrar em ministração');if(action==='build')return applyFlow({...base,dynamics:'build'},'Crescendo progressivo');if(action==='drop')return applyFlow({...base,dynamics:'drop'},'Corte total / somente voz');if(action==='band')return applyFlow({...base,dynamics:'full'},'Banda completa entra');if(action==='ending')return applyFlow({...base,mode:'ending'},'Preparar final agora')}
function renderSelects(){const lists=getSetlists(),teams=getTeams();$('room-setlist-select').innerHTML=lists.length?lists.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} • ${(x.songs||[]).length} músicas</option>`).join(''):'<option value="">Nenhum repertório disponível</option>';$('room-team-select').innerHTML='<option value="">Sem equipe</option>'+teams.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}
function renderFlow(r,isDirector){const flow=Object.assign(defaultFlow(),r?.flow||{}),song=currentSong(r),sections=extractSections(song),sectionSelect=$('flow-section-select');if(sectionSelect){const selected=flow.section||sectionSelect.value||'';sectionSelect.innerHTML='<option value="">Automática / atual</option>'+sections.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');sectionSelect.value=sections.includes(selected)?selected:''}if($('flow-dynamics'))$('flow-dynamics').value=flow.dynamics||'normal';if($('flow-modulation'))$('flow-modulation').value=String(Number(flow.modulation)||0);if($('flow-mode'))$('flow-mode').value=flow.mode||'normal';if($('flow-live-state'))$('flow-live-state').textContent=flow.mode==='normal'&&flow.dynamics==='normal'&&!flow.modulation&&!flow.section?'Fluxo normal':`${modeLabels[flow.mode]||flow.mode} ativo`;if($('flow-summary-section'))$('flow-summary-section').textContent=flow.section||'Automática';if($('flow-summary-mode'))$('flow-summary-mode').textContent=modeLabels[flow.mode]||'Normal';if($('flow-summary-dynamics'))$('flow-summary-dynamics').textContent=dynamicsLabels[flow.dynamics]||'Normal';if($('flow-summary-modulation'))$('flow-summary-modulation').textContent=Number(flow.modulation)?`${Number(flow.modulation)>0?'+':''}${flow.modulation} semitom${Math.abs(Number(flow.modulation))===1?'':'s'}`:'Original';if($('flow-history'))$('flow-history').innerHTML=(flow.history||[]).length?(flow.history||[]).map(item=>`<article><strong>${esc(item.label)}</strong><small>${new Date(item.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></article>`).join(''):'<p class="section-subtitle">Nenhum comando avançado enviado.</p>';if($('worship-flow-panel'))$('worship-flow-panel').classList.toggle('readonly',!isDirector)}
function render(){if(!document.body.matches('[data-page="sala-live"]'))return;const r=room(),list=currentSetlist(r),member=activeMember(),isDirector=current?.role==='director'&&r?.directorId===current?.memberId;const active=r&&r.status==='active';$('room-stat-status').textContent=active?'Ativa':'Inativa';$('room-stat-code').textContent=active?r.code:'—';$('room-stat-members').textContent=active?(r.members||[]).length:0;$('room-stat-position').textContent=active&&list?`${Math.min(r.index+1,list.songs.length)} / ${list.songs.length}`:'0 / 0';$('room-role-badge').textContent=isDirector?'Diretor musical':active?'Músico conectado':'Sem sala';$('room-role-badge').dataset.role=isDirector?'director':active?'member':'';$('director-panel').hidden=!isDirector;$('end-room-btn').disabled=!isDirector;$('copy-room-code').disabled=!active;$('leave-room-btn').disabled=!active;$('create-room-btn').disabled=!!active;$('join-room-btn').disabled=!!active;$('joined-room-summary').hidden=!active||isDirector;if(active){$('joined-room-name').textContent=r.name;$('joined-room-song').textContent=list?.songs?.[r.index]?.title?`Música atual: ${list.songs[r.index].title}`:'Aguardando direção musical...';const banner=$('room-command-banner');banner.hidden=!r.command;banner.textContent=r.command||''}if(isDirector&&list){const song=list.songs?.[r.index];$('director-current-title').textContent=song?.title||'Sem música';$('director-current-meta').textContent=song?`${song.artist||'Sem artista'} • Tom ${song.key||song.originalKey||'—'} • ${r.index+1}/${list.songs.length}`:'—';$('director-prev').disabled=r.index<=0;$('director-next').disabled=r.index>=list.songs.length-1}
 const members=r?.members||[];$('room-member-list').innerHTML=members.length?members.map(m=>`<article class="room-member"><div><strong>${esc(m.name)}</strong><small>${esc(m.instrument)} • ${m.role==='director'?'Diretor':'Músico'}</small></div><span class="room-member-status">conectado</span></article>`).join(''):'<p class="section-subtitle">Nenhum participante conectado.</p>';if(member){$('room-display-name').value=member.name||'';$('room-instrument').value=member.instrument||'Outro'}renderFlow(r,isDirector)}
function bind(){renderSelects();$('create-room-btn').onclick=createRoom;$('join-room-btn').onclick=joinRoom;$('leave-room-btn').onclick=leaveRoom;$('end-room-btn').onclick=endRoom;$('copy-room-code').onclick=async()=>{const r=room();if(!r)return;try{await navigator.clipboard.writeText(r.code);toast('Código copiado.')}catch{toast(`Código: ${r.code}`)}};$('director-prev').onclick=()=>move(-1);$('director-next').onclick=()=>move(1);$('director-send-message').onclick=()=>sendCommand($('director-message').value);$('quick-command-grid').onclick=e=>{const b=e.target.closest('[data-command]');if(b)sendCommand(b.dataset.command)};$('worship-flow-panel')?.addEventListener('click',e=>{const b=e.target.closest('[data-flow-action]');if(b)handleFlowAction(b.dataset.flowAction)});channel?.addEventListener('message',()=>{rooms=read(ROOMS_KEY,{});Object.keys(rooms).forEach(k=>rooms[k]=normalizeRoom(rooms[k]));render()});window.addEventListener('storage',e=>{if(e.key===ROOMS_KEY){rooms=read(ROOMS_KEY,{});Object.keys(rooms).forEach(k=>rooms[k]=normalizeRoom(rooms[k]));render()}})}
document.addEventListener('DOMContentLoaded',()=>{if(!document.body.matches('[data-page="sala-live"]'))return;bind();startHeartbeat();render()});
window.StageMusicLiveRoom={getCurrent:()=>room(),getContext:()=>current,move,sendCommand,applyFlow};
})();
