(function(){'use strict';const $=id=>document.getElementById(id);let ctx=null,metroTimer=null,beat=0,nextBeat=0,toneOsc=null,tapTimes=[],harmonic=false;const NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
function audio(){try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}catch{return null}}
function click(accent=false){const c=audio();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.frequency.value=accent?1200:850;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(accent?.18:.1,c.currentTime+.003);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.055);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.06)}
function bpm(){return Math.min(240,Math.max(40,Number($('tool-bpm-range').value)||120))}function syncBpm(v){v=Math.min(240,Math.max(40,Math.round(v)));$('tool-bpm-range').value=v;$('tool-bpm').textContent=v}
function tick(){click(beat===0);document.querySelectorAll('#beat-lights i').forEach((x,i)=>x.classList.toggle('active',i===beat));beat=(beat+1)%4}
function startMetro(){if(metroTimer)return;beat=0;tick();metroTimer=setInterval(tick,60000/bpm());$('metronome-toggle').textContent='Ⅱ Pausar'}function stopMetro(){clearInterval(metroTimer);metroTimer=null;document.querySelectorAll('#beat-lights i').forEach(x=>x.classList.remove('active'));$('metronome-toggle').textContent='▶ Iniciar'}function restart(){if(metroTimer){stopMetro();startMetro()}}
function tap(){const now=performance.now();tapTimes=tapTimes.filter(t=>now-t<2500);tapTimes.push(now);if(tapTimes.length>1){const gaps=tapTimes.slice(1).map((t,i)=>t-tapTimes[i]);syncBpm(60000/(gaps.reduce((a,b)=>a+b,0)/gaps.length));restart()}}
function countIn(){let n=0;$('count-in').disabled=true;const run=()=>{click(n===0);$('count-in').textContent=`${n+1} / 4`;n++;if(n<4)setTimeout(run,60000/bpm());else setTimeout(()=>{$('count-in').textContent='Contar 4';$('count-in').disabled=false},60000/bpm())};run()}
function freq(note,oct){const midi=(oct+1)*12+NOTES.indexOf(note);return 440*Math.pow(2,(midi-69)/12)}function toneLabel(){const f=freq($('tone-note').value,Number($('tone-octave').value));$('tone-frequency').textContent=`${$('tone-note').value}${$('tone-octave').value} • ${f.toFixed(2).replace('.',',')} Hz`;return f}
function stopTone(){if(toneOsc){try{toneOsc.stop()}catch{}toneOsc=null}$('tone-toggle').textContent='Ouvir tom'}function toggleTone(){if(toneOsc){stopTone();return}const c=audio();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=toneLabel();g.gain.value=.12;o.connect(g).connect(c.destination);o.start();toneOsc=o;$('tone-toggle').textContent='Parar tom'}
function norm(k){return NOTES.indexOf(String(k||'').replace('Db','C#').replace('Eb','D#').replace('Gb','F#').replace('Ab','G#').replace('Bb','A#').match(/^[A-G]#?/)?.[0]||'C')}
function capo(){const key=$('live-key')?.textContent||'C',shape=$('capo-shape').value;let fret=(norm(key)-norm(shape)+12)%12;$('capo-current-key').textContent=key;$('capo-result').innerHTML=fret===0?`Toque na forma de <b>${shape}</b> sem capotraste.`:`Use a forma de <b>${shape}</b> com capotraste na <b>${fret}ª casa</b>.`}
function roman(n,minor=false){return ['I','♭II','II','♭III','III','IV','♭V','V','♭VI','VI','♭VII','VII'][n]+(minor?'m':'')}
function convert(){const pre=$('live-content'),key=$('live-key')?.textContent||'C';if(!pre)return;harmonic=!harmonic;if(harmonic){pre.dataset.originalHtml=pre.innerHTML;const root=norm(key);pre.querySelectorAll('.chord').forEach(el=>{el.textContent=el.textContent.replace(/\b([A-G](?:#|b)?)(m?[^\s]*)/g,(all,n,s)=>roman((norm(n)-root+12)%12,s.startsWith('m'))+s.replace(/^m/,''))});$('harmonic-toggle').textContent='Mostrar acordes';$('harmonic-summary').textContent='Visualização em graus ativa. A cifra original permanece preservada.'}else{if(pre.dataset.originalHtml)pre.innerHTML=pre.dataset.originalHtml;$('harmonic-toggle').textContent='Mostrar graus';$('harmonic-summary').textContent='Os acordes serão convertidos em graus relativos ao tom da música.'}}
document.addEventListener('DOMContentLoaded',()=>{if(!$('music-tools-dialog'))return;const dialog=$('music-tools-dialog');$('music-tools-open').onclick=()=>{syncBpm(Number($('live-bpm')?.textContent)||120);capo();dialog.showModal()};dialog.addEventListener('close',()=>{stopMetro();stopTone()});$('metronome-toggle').onclick=()=>metroTimer?stopMetro():startMetro();$('tap-tempo').onclick=tap;$('count-in').onclick=countIn;$('tool-bpm-range').oninput=e=>{syncBpm(e.target.value);restart()};$('tone-note').onchange=toneLabel;$('tone-octave').onchange=toneLabel;$('tone-toggle').onclick=toggleTone;$('capo-shape').onchange=capo;$('harmonic-toggle').onclick=convert;toneLabel()});})();
