(function(){
 const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const fmt=iso=>{const d=new Date(iso);return Number.isNaN(d)?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(d)};
 document.addEventListener('DOMContentLoaded',()=>{if(!document.body.matches('[data-page="buscar-cifra"]'))return;const db=window.StageMusicLocalDB,$=id=>document.getElementById(id),input=$('search-local-input'),filter=$('library-filter'),sort=$('library-sort'),results=$('search-local-results'),counter=$('search-local-counter'),tagBox=$('library-tag-filters'),dialog=$('song-preview-dialog'),preview=$('song-preview-content');let activeTag='';
  const updateStats=()=>{const s=db.getStats();$('library-total').textContent=s.songsCount;$('library-favorites').textContent=s.favoritesCount;$('library-tags').textContent=s.tagsCount;$('library-recent').textContent=s.recentCount};
  const renderTags=()=>{tagBox.innerHTML=db.getAllTags().map(t=>`<button class="tag-filter" data-tag="${esc(t)}">#${esc(t)}</button>`).join('')};
  const getSongs=()=>{let songs=db.searchSongs(input.value);if(filter.value==='favorites')songs=songs.filter(s=>db.isFavorite(s.id));if(filter.value==='recent'){const ids=db.getRecentIds();songs=songs.filter(s=>ids.includes(s.id)).sort((a,b)=>ids.indexOf(a.id)-ids.indexOf(b.id))}if(activeTag)songs=songs.filter(s=>(s.tags||[]).some(t=>t===activeTag));if(sort.value==='title')songs.sort((a,b)=>a.title.localeCompare(b.title,'pt-BR'));if(sort.value==='artist')songs.sort((a,b)=>a.artist.localeCompare(b.artist,'pt-BR'));if(sort.value==='key')songs.sort((a,b)=>a.key.localeCompare(b.key,'pt-BR'));return songs};
  const render=()=>{const songs=getSongs();counter.textContent=`${songs.length} ${songs.length===1?'cifra encontrada':'cifras encontradas'}`;if(!songs.length){results.innerHTML=`<article class="library-empty-state"><span>♫</span><h3>Nenhuma cifra encontrada</h3><p>Ajuste os filtros ou adicione uma nova música à sua biblioteca.</p><a href="inserir-cifra.html" class="btn-primary">Criar cifra</a></article>`;updateStats();return}results.innerHTML=songs.map(s=>`<article class="song-card" data-id="${esc(s.id)}"><div class="song-card-top"><div class="song-key">${esc(s.key)}</div><button class="favorite-btn ${db.isFavorite(s.id)?'active':''}" data-action="favorite" title="Favoritar">★</button></div><h3>${esc(s.title)}</h3><p>${esc(s.artist)}</p><div class="song-meta"><span>${esc(s.bpm)} BPM</span><span>Atualizada ${esc(fmt(s.updatedAt))}</span></div><div class="song-tags">${(s.tags||[]).slice(0,4).map(t=>`<span>#${esc(t)}</span>`).join('')}</div><div class="song-actions"><button class="btn-secondary" data-action="preview">Visualizar</button><a class="btn-outline" href="inserir-cifra.html">Editar</a></div></article>`).join('');updateStats()};
  const openSong=s=>{db.markRecent(s.id);preview.innerHTML=`<div class="dialog-song-head"><div class="song-key">${esc(s.key)}</div><div><h2>${esc(s.title)}</h2><p>${esc(s.artist)} • ${esc(s.bpm)} BPM</p></div></div><div class="song-tags">${(s.tags||[]).map(t=>`<span>#${esc(t)}</span>`).join('')}</div>${s.notes?`<aside class="song-notes">${esc(s.notes)}</aside>`:''}<pre class="song-content">${esc(s.content||'Cifra ainda sem conteúdo.')}</pre>`;dialog.showModal();render()};
  [input,filter,sort].forEach(el=>el.addEventListener(el===input?'input':'change',render));document.querySelector('.tag-filter-wrap').addEventListener('click',e=>{const b=e.target.closest('[data-tag]');if(!b)return;activeTag=b.dataset.tag;document.querySelectorAll('.tag-filter').forEach(x=>x.classList.toggle('active',x.dataset.tag===activeTag));render()});results.addEventListener('click',e=>{const card=e.target.closest('.song-card');if(!card)return;const s=db.getSongById(card.dataset.id);if(e.target.closest('[data-action="favorite"]')){db.toggleFavorite(s.id);render()}else if(e.target.closest('[data-action="preview"]'))openSong(s)});$('library-reset').addEventListener('click',()=>{input.value='';filter.value='all';sort.value='updated';activeTag='';document.querySelectorAll('.tag-filter').forEach(x=>x.classList.toggle('active',x.dataset.tag===''));render()});renderTags();render();
 });
})();
