(function(){
'use strict';
const KEY='stage_music_setlists_v1',ACTIVE='stage_music_active_setlist';
const $=id=>document.getElementById(id), now=()=>new Date().toISOString();
const safeGet=()=>{try{const v=window.StageMusicSafeStorage?.get(KEY,[])??JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
const safeSet=v=>window.StageMusicSafeStorage?.set(KEY,v)??(localStorage.setItem(KEY,JSON.stringify(v)),true);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let lists=safeGet(),activeId=lists[0]?.id||null,dragIndex=null,search='';
const save=()=>{safeSet(lists);renderAll()};
const current=()=>lists.find(x=>x.id===activeId)||null;
const durationText=m=>{m=Math.max(0,Math.round(Number(m)||0));return m>=60?`${Math.floor(m/60)}h ${m%60}min`:`${m} min`};
const totalMinutes=l=>(l?.songs||[]).reduce((n,s)=>n+(Number(s.duration)||0),0);
const toast=t=>{const el=$('stage-toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)};
const normalize=l=>({id:l.id||`set_${Date.now()}`,name:l.name||'Novo repertório',date:l.date||'',type:l.type||'Culto',status:l.status||'draft',notes:l.notes||'',songs:Array.isArray(l.songs)?l.songs:[],createdAt:l.createdAt||now(),updatedAt:l.updatedAt||now()});
lists=lists.map(normalize);
function stats(){const songs=lists.reduce((n,l)=>n+l.songs.length,0),mins=lists.reduce((n,l)=>n+totalMinutes(l),0),ready=lists.flatMap(l=>l.songs).filter(s=>s.rehearsed).length; $('stat-setlists').textContent=lists.length;$('stat-songs').textContent=songs;$('stat-duration').textContent=durationText(mins);$('stat-ready').textContent=songs?`${Math.round(ready/songs*100)}%`:'0%'}
function renderNav(){const filtered=lists.filter(l=>l.name.toLowerCase().includes(search.toLowerCase()));$('setlist-list').innerHTML=filtered.length?filtered.map(l=>`<button class="setlist-nav-item ${l.id===activeId?'active':''}" data-id="${esc(l.id)}"><strong>${esc(l.name)}</strong><small>${l.songs.length} músicas • ${durationText(totalMinutes(l))} • ${esc(l.type)}</small></button>`).join(''):'<div class="empty-song-list">Nenhum repertório encontrado.</div>';}
function renderEditor(){const l=current(),empty=$('setlist-empty'),content=$('setlist-content');$('duplicate-setlist-btn').disabled=!l;if(!l){empty.hidden=false;content.hidden=true;return}empty.hidden=true;content.hidden=false;$('setlist-name').value=l.name;$('setlist-date').value=l.date;$('setlist-type').value=l.type;$('setlist-status').value=l.status;$('setlist-notes').value=l.notes;$('setlist-song-count').textContent=`${l.songs.length} ${l.songs.length===1?'música':'músicas'}`;$('setlist-total-time').textContent=durationText(totalMinutes(l));$('setlist-updated').textContent=`Atualizado ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(l.updatedAt))}`;renderSongs(l)}
function renderSongs(l){$('setlist-songs').innerHTML=l.songs.length?l.songs.map((item,i)=>`<article class="setlist-song-row" draggable="true" data-index="${i}"><span class="drag-handle" title="Arrastar">☷ ${i+1}</span><div class="song-identity"><strong>${esc(item.title)}</strong><small>${esc(item.artist||'Sem artista')} • original ${esc(item.originalKey||item.key||'C')}</small></div><input class="compact-input" data-field="key" value="${esc(item.key||'C')}" aria-label="Tom"><input class="compact-input" data-field="duration" type="number" min="0" max="60" step="0.5" value="${esc(item.duration||4)}" aria-label="Duração em minutos"><select class="compact-select" data-field="rehearsed"><option value="false" ${!item.rehearsed?'selected':''}>A ensaiar</option><option value="true" ${item.rehearsed?'selected':''}>Pronta</option></select><div class="row-actions"><button class="icon-btn" data-action="up" title="Subir">↑</button><button class="icon-btn" data-action="down" title="Descer">↓</button><button class="icon-btn" data-action="remove" title="Remover">✕</button></div></article>`).join(''):'<div class="empty-song-list"><strong>Repertório vazio</strong><p>Adicione músicas da sua biblioteca para preparar a apresentação.</p></div>'}
function renderAll(){stats();renderNav();renderEditor()}
function createList(name,date,type){const l=normalize({id:`set_${Date.now()}`,name,date,type,songs:[]});lists.unshift(l);activeId=l.id;save();toast('Repertório criado')}
function updateCurrent(patch){const l=current();if(!l)return;Object.assign(l,patch,{updatedAt:now()});safeSet(lists);renderNav();stats()}
function move(from,to){const l=current();if(!l||to<0||to>=l.songs.length)return;const [x]=l.songs.splice(from,1);l.songs.splice(to,0,x);l.updatedAt=now();save()}
document.addEventListener('DOMContentLoaded',()=>{if(!document.body.matches('[data-page="minhas-listas"]'))return;
 const dlg=$('setlist-dialog'),picker=$('song-picker-dialog');
 const openNew=()=>{ $('new-setlist-name').value='';$('new-setlist-date').value=new Date().toISOString().slice(0,10);dlg.showModal();setTimeout(()=>$('new-setlist-name').focus(),60)};
 $('new-setlist-btn').onclick=openNew;document.querySelector('[data-action="new"]').onclick=openNew;
 $('setlist-form').addEventListener('submit',e=>{e.preventDefault();const n=$('new-setlist-name').value.trim();if(!n)return;createList(n,$('new-setlist-date').value,$('new-setlist-type').value);dlg.close()});
 $('setlist-search').addEventListener('input',e=>{search=e.target.value;renderNav()});$('setlist-list').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;activeId=b.dataset.id;renderAll()});
 ['name','date','type','status','notes'].forEach(f=>{$(`setlist-${f}`).addEventListener(f==='name'||f==='notes'?'input':'change',e=>updateCurrent({[f]:e.target.value}))});
 $('duplicate-setlist-btn').onclick=()=>{const l=current();if(!l)return;const c=normalize({...JSON.parse(JSON.stringify(l)),id:`set_${Date.now()}`,name:`${l.name} — cópia`,createdAt:now(),updatedAt:now()});lists.unshift(c);activeId=c.id;save();toast('Repertório duplicado')};
 $('delete-setlist-btn').onclick=()=>{const l=current();if(!l||!confirm(`Excluir “${l.name}”?`))return;lists=lists.filter(x=>x.id!==l.id);activeId=lists[0]?.id||null;save();toast('Repertório excluído')};
 const renderPicker=()=>{const q=$('song-picker-search').value.trim(),songs=window.StageMusicLocalDB.searchSongs(q),l=current();$('song-picker-list').innerHTML=songs.length?songs.map(s=>{const added=l?.songs.some(x=>x.songId===s.id);return `<article class="song-picker-item"><div><strong>${esc(s.title)}</strong><p>${esc(s.artist)} • ${esc(s.key)} • ${esc(s.bpm)} BPM</p></div><button class="btn ${added?'btn-secondary':'btn-primary'}" data-song-id="${esc(s.id)}" ${added?'disabled':''}>${added?'Adicionada':'Adicionar'}</button></article>`}).join(''):'<div class="empty-song-list">Nenhuma cifra encontrada na biblioteca.</div>'};
 $('add-song-btn').onclick=()=>{renderPicker();picker.showModal()};$('close-song-picker').onclick=()=>picker.close();$('song-picker-search').oninput=renderPicker;$('song-picker-list').onclick=e=>{const b=e.target.closest('[data-song-id]');if(!b)return;const s=window.StageMusicLocalDB.getSongById(b.dataset.songId),l=current();if(!s||!l)return;l.songs.push({songId:s.id,title:s.title,artist:s.artist,key:s.key,originalKey:s.key,bpm:s.bpm,duration:4,rehearsed:false,notes:''});l.updatedAt=now();save();renderPicker();toast('Música adicionada')};
 $('setlist-songs').addEventListener('change',e=>{const row=e.target.closest('[data-index]'),l=current();if(!row||!l)return;const item=l.songs[Number(row.dataset.index)],field=e.target.dataset.field;if(!field)return;item[field]=field==='duration'?Math.max(0,Number(e.target.value)||0):field==='rehearsed'?e.target.value==='true':e.target.value;l.updatedAt=now();save()});
 $('setlist-songs').addEventListener('click',e=>{const row=e.target.closest('[data-index]'),a=e.target.closest('[data-action]'),l=current();if(!row||!a||!l)return;const i=Number(row.dataset.index);if(a.dataset.action==='remove'){l.songs.splice(i,1);l.updatedAt=now();save()}if(a.dataset.action==='up')move(i,i-1);if(a.dataset.action==='down')move(i,i+1)});
 $('setlist-songs').addEventListener('dragstart',e=>{const r=e.target.closest('[data-index]');dragIndex=r?Number(r.dataset.index):null});$('setlist-songs').addEventListener('dragover',e=>e.preventDefault());$('setlist-songs').addEventListener('drop',e=>{e.preventDefault();const r=e.target.closest('[data-index]');if(r&&dragIndex!==null)move(dragIndex,Number(r.dataset.index));dragIndex=null});
 $('start-live-btn').onclick=()=>{const l=current();if(!l||!l.songs.length){toast('Adicione ao menos uma música');return}try{localStorage.setItem(ACTIVE,JSON.stringify({...l,startedAt:now()}))}catch{}location.href='modo-live.html'};
 renderAll();
});
})();
