(function(){
'use strict';
const KEY='stage_music_teams_v1',SETLIST_KEY='stage_music_setlists_v1';
const $=id=>document.getElementById(id),now=()=>new Date().toISOString();
const safeParse=(v,f)=>{try{return JSON.parse(v)??f}catch{return f}};
const read=()=>{const v=window.StageMusicSafeStorage?.get?.(KEY,null)??safeParse(localStorage.getItem(KEY)||'[]',[]);return Array.isArray(v)?v:[]};
const write=v=>window.StageMusicSafeStorage?.set?.(KEY,v)??(localStorage.setItem(KEY,JSON.stringify(v)),true);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const roleLabels={admin:'Administrador',director:'Diretor musical',editor:'Editor',musician:'Músico',viewer:'Somente leitura'};
const roleDescriptions={admin:'Controle total da equipe, membros e dados.',director:'Pode dirigir repertórios e apresentações.',editor:'Pode editar cifras e repertórios compartilhados.',musician:'Pode visualizar repertórios e usar o Modo Live.',viewer:'Visualização sem alterações.'};
const normalizeMember=m=>({id:m.id||`member_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:m.name||'Músico',email:m.email||'',role:m.role||'musician',instrument:m.instrument||'Outro',status:m.status||'active',joinedAt:m.joinedAt||now()});
const code=()=>`STG-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
const normalize=t=>({id:t.id||`team_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:t.name||'Nova equipe',type:t.type||'Banda',description:t.description||'',ownerRole:t.ownerRole||'admin',code:t.code||code(),members:Array.isArray(t.members)?t.members.map(normalizeMember):[],invites:Array.isArray(t.invites)?t.invites:[],setlistIds:Array.isArray(t.setlistIds)?t.setlistIds:[],createdAt:t.createdAt||now(),updatedAt:t.updatedAt||now()});
let teams=read().map(normalize),activeId=teams[0]?.id||null,search='';
const current=()=>teams.find(t=>t.id===activeId)||null;
const toast=msg=>{const el=$('team-toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)};
const save=(options={})=>{write(teams);renderAll();window.StageMusicWorkspaceCloud?.saveTeams?.(teams,options).catch(err=>console.warn('Proteção permanente de equipes:',err?.message||err));window.StageMusicCloudSync?.syncTeams?.(teams).catch(err=>console.warn('Sync opcional de equipes:',err?.message||err));};
function stats(){const members=teams.reduce((n,t)=>n+t.members.length,0),directors=teams.reduce((n,t)=>n+t.members.filter(m=>m.role==='director').length,0),invites=teams.reduce((n,t)=>n+t.invites.filter(i=>i.active!==false).length,0);$('team-stat-total').textContent=teams.length;$('team-stat-members').textContent=members;$('team-stat-directors').textContent=directors;$('team-stat-invites').textContent=invites}
function renderNav(){const list=teams.filter(t=>t.name.toLowerCase().includes(search.toLowerCase()));$('team-list').innerHTML=list.length?list.map(t=>`<button class="team-nav-item ${t.id===activeId?'active':''}" data-team-id="${esc(t.id)}"><strong>${esc(t.name)}</strong><small>${t.members.length} membros • ${esc(t.type)}</small></button>`).join(''):'<div class="section-subtitle">Nenhuma equipe encontrada.</div>'}
function renderPermissions(){const t=current();$('permission-summary').innerHTML=Object.entries(roleLabels).map(([role,label])=>`<article class="permission-card"><strong>${esc(label)}</strong><small>${esc(roleDescriptions[role])}</small>${t?.ownerRole===role?'<span class="status-pill">Seu papel</span>':''}</article>`).join('')}
function renderMembers(){const t=current();if(!t)return;$('member-list').innerHTML=t.members.length?t.members.map((m,i)=>`<article class="member-row" data-member-index="${i}"><div><strong>${esc(m.name)}</strong><small>${esc(m.email||'Sem e-mail')} • ${esc(m.instrument)}</small></div><select data-field="role"><option value="director" ${m.role==='director'?'selected':''}>Diretor musical</option><option value="editor" ${m.role==='editor'?'selected':''}>Editor</option><option value="musician" ${m.role==='musician'?'selected':''}>Músico</option><option value="viewer" ${m.role==='viewer'?'selected':''}>Somente leitura</option></select><select data-field="instrument"><option ${m.instrument==='Vocal'?'selected':''}>Vocal</option><option ${m.instrument==='Teclado'?'selected':''}>Teclado</option><option ${m.instrument==='Guitarra'?'selected':''}>Guitarra</option><option ${m.instrument==='Violão'?'selected':''}>Violão</option><option ${m.instrument==='Baixo'?'selected':''}>Baixo</option><option ${m.instrument==='Bateria'?'selected':''}>Bateria</option><option ${m.instrument==='Sopros'?'selected':''}>Sopros</option><option ${m.instrument==='Direção musical'?'selected':''}>Direção musical</option><option ${m.instrument==='Outro'?'selected':''}>Outro</option></select><button class="icon-btn" data-action="remove-member" title="Remover">✕</button></article>`).join(''):'<div class="section-subtitle">Nenhum membro adicionado ainda.</div>'}
function renderEditor(){const t=current(),empty=$('team-empty'),content=$('team-content');if(!t){empty.hidden=false;content.hidden=true;return}empty.hidden=true;content.hidden=false;$('team-name').value=t.name;$('team-type').value=t.type;$('team-owner-role').value=t.ownerRole;$('team-description').value=t.description;$('team-summary').textContent=`${t.members.length} membros • criada em ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(t.createdAt))}`;$('team-code').textContent=t.code;let setlists=[];try{setlists=JSON.parse(localStorage.getItem(SETLIST_KEY)||'[]')}catch{}const linked=setlists.filter(list=>list.teamId===t.id).length;$('team-setlist-count').textContent=`${linked} ${linked===1?'repertório':'repertórios'}`;renderPermissions();renderMembers()}
function renderAll(){stats();renderNav();renderEditor()}
function update(patch){const t=current();if(!t)return;Object.assign(t,patch,{updatedAt:now()});save()}
function createTeam(name,type){const auth=window.StageMusicAuth?.getState?.()||{};const owner=normalizeMember({name:auth.name||'Administrador',email:auth.email||'',role:'admin',instrument:'Direção musical'});const t=normalize({name,type,members:[owner]});teams.unshift(t);activeId=t.id;save({immediate:true});toast('Equipe criada e protegida na conta')}
document.addEventListener('DOMContentLoaded',()=>{if(!document.body.matches('[data-page="equipes"]'))return;
 const teamDlg=$('team-dialog'),memberDlg=$('member-dialog'),joinDlg=$('join-team-dialog');
 const openTeam=()=>{teamDlg.showModal();setTimeout(()=>$('new-team-name').focus(),50)};
 $('new-team-btn').onclick=openTeam;document.querySelector('[data-action="new-team"]').onclick=openTeam;
 $('team-form').addEventListener('submit',e=>{e.preventDefault();const name=$('new-team-name').value.trim();if(!name)return;createTeam(name,$('new-team-type').value);teamDlg.close();e.target.reset()});
 $('team-search').addEventListener('input',e=>{search=e.target.value;renderNav()});
 $('team-list').addEventListener('click',e=>{const b=e.target.closest('[data-team-id]');if(!b)return;activeId=b.dataset.teamId;renderAll()});
 $('team-name').addEventListener('input',e=>update({name:e.target.value}));$('team-type').addEventListener('change',e=>update({type:e.target.value}));$('team-owner-role').addEventListener('change',e=>update({ownerRole:e.target.value}));$('team-description').addEventListener('input',e=>update({description:e.target.value}));
 $('delete-team-btn').onclick=()=>{const t=current();if(!t||!confirm(`Excluir a equipe “${t.name}”?`))return;const removedId=t.id;teams=teams.filter(x=>x.id!==removedId);activeId=teams[0]?.id||null;write(teams);renderAll();window.StageMusicWorkspaceCloud?.deleteTeam?.(removedId).catch(err=>console.warn('Exclusão permanente da equipe:',err?.message||err));toast('Equipe excluída deste aparelho e da nuvem')};
 $('generate-invite-btn').onclick=()=>{const t=current();if(!t)return;t.code=code();t.invites.push({code:t.code,active:true,createdAt:now()});t.updatedAt=now();save();toast('Novo código de convite gerado')};
 $('copy-team-code').onclick=async()=>{const t=current();if(!t)return;try{await navigator.clipboard.writeText(t.code);toast('Código copiado')}catch{prompt('Copie o código:',t.code)}};
 $('add-member-btn').onclick=()=>memberDlg.showModal();$('member-form').addEventListener('submit',e=>{e.preventDefault();const t=current();if(!t)return;t.members.push(normalizeMember({name:$('member-name').value.trim(),email:$('member-email').value.trim(),role:$('member-role').value,instrument:$('member-instrument').value}));t.updatedAt=now();save();memberDlg.close();e.target.reset();toast('Membro adicionado')});
 $('member-list').addEventListener('change',e=>{const row=e.target.closest('[data-member-index]'),t=current();if(!row||!t)return;const member=t.members[Number(row.dataset.memberIndex)],field=e.target.dataset.field;if(!field)return;member[field]=e.target.value;t.updatedAt=now();save()});
 $('member-list').addEventListener('click',e=>{const row=e.target.closest('[data-member-index]'),btn=e.target.closest('[data-action="remove-member"]'),t=current();if(!row||!btn||!t)return;t.members.splice(Number(row.dataset.memberIndex),1);t.updatedAt=now();save();toast('Membro removido')});
 $('join-team-btn').onclick=()=>joinDlg.showModal();$('join-team-form').addEventListener('submit',e=>{e.preventDefault();const q=$('join-team-code').value.trim().toUpperCase(),found=teams.find(t=>t.code.toUpperCase()===q);if(!found){alert('Código não encontrado neste dispositivo.');return}activeId=found.id;joinDlg.close();renderAll();toast(`Equipe ${found.name} aberta`)});
 renderAll();
});
})();
