const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const errors=[],warnings=[];
const info=JSON.parse(fs.readFileSync(path.join(root,'BUILD-INFO.json'))),pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json')));
if(`v${pkg.version}`!==info.version)errors.push('Versões divergentes.');
const htmls=fs.readdirSync(root).filter(x=>x.endsWith('.html'));const attrs=['js/build-info.js','js/resilience.js','data-build-info'];
for(const file of htmls){const html=fs.readFileSync(path.join(root,file),'utf8');for(const a of attrs)if(!html.includes(a))errors.push(`${file}: ausente ${a}`);for(const m of html.matchAll(/(?:href|src)=['"]([^'"]+)['"]/g)){const u=m[1];if(/^(https?:|mailto:|#|data:)/.test(u))continue;const clean=u.split(/[?#]/)[0];if(clean&&!fs.existsSync(path.resolve(root,clean)))errors.push(`${file}: referência inexistente ${clean}`)}}
for(const required of ['service-worker.js','manifest.json','js/resilience.js','css/global.css','css/setlists.css','js/setlists.js'])if(!fs.existsSync(path.join(root,required)))errors.push(`Arquivo essencial ausente: ${required}`);
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');if(!sw.includes(info.versionNumber.replaceAll('.','-')))warnings.push('Nome do cache pode não refletir a versão.');
if(info.phase===5){const page=fs.readFileSync(path.join(root,'minhas-listas.html'),'utf8');for(const token of ['setlist-list','setlist-songs','song-picker-dialog','js/setlists.js'])if(!page.includes(token))errors.push('Fase 5 incompleta: '+token);}
if(errors.length){console.error('AUDITORIA REPROVADA\n'+errors.join('\n'));process.exit(1)}console.log(`AUDITORIA APROVADA — ${info.app} ${info.version} | ${htmls.length} páginas | ${info.date} ${info.time}`);if(warnings.length)console.warn(warnings.join('\n'));
