const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const errors=[],warnings=[];
const info=JSON.parse(fs.readFileSync(path.join(root,'BUILD-INFO.json'))),pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json')));
if(`v${pkg.version}`!==info.version)errors.push('Versões divergentes.');
const htmls=fs.readdirSync(root).filter(x=>x.endsWith('.html'));const attrs=['js/build-info.js','js/resilience.js','data-build-info'];
for(const file of htmls){const html=fs.readFileSync(path.join(root,file),'utf8');for(const a of attrs)if(!html.includes(a))errors.push(`${file}: ausente ${a}`);for(const m of html.matchAll(/(?:href|src)=['"]([^'"]+)['"]/g)){const u=m[1];if(/^(https?:|mailto:|#|data:)/.test(u))continue;const clean=u.split(/[?#]/)[0];if(clean&&!fs.existsSync(path.resolve(root,clean)))errors.push(`${file}: referência inexistente ${clean}`)}}
for(const required of ['service-worker.js','manifest.json','js/resilience.js','css/global.css','css/setlists.css','js/setlists.js','js/live-mode.js'])if(!fs.existsSync(path.join(root,required)))errors.push(`Arquivo essencial ausente: ${required}`);
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');if(!sw.includes(info.versionNumber.replaceAll('.','-')))warnings.push('Nome do cache pode não refletir a versão.');
if(info.phase>=5){const page=fs.readFileSync(path.join(root,'minhas-listas.html'),'utf8');for(const token of ['setlist-list','setlist-songs','song-picker-dialog','js/setlists.js'])if(!page.includes(token))errors.push('Fase 5 incompleta: '+token);}
if(info.phase>=6){const page=fs.readFileSync(path.join(root,'modo-live.html'),'utf8');for(const token of ['live-reader','live-controls','js/live-mode.js','live-wake-btn'])if(!page.includes(token))errors.push('Fase 6 incompleta: '+token);}
if(info.phase>=9){const page=fs.readFileSync(path.join(root,'modo-live.html'),'utf8');for(const token of ['instrument-profile-dialog','instrument-profile-open','instrument-note-banner','js/instrument-profiles.js'])if(!page.includes(token))errors.push('Fase 9 incompleta: '+token);if(!fs.existsSync(path.join(root,'js/instrument-profiles.js')))errors.push('Fase 9 JS ausente.');}
if(info.phase>=8){const page=fs.readFileSync(path.join(root,'modo-live.html'),'utf8');for(const token of ['music-tools-dialog','metronome-toggle','tap-tempo','count-in','capo-result','harmonic-toggle','js/music-tools.js'])if(!page.includes(token))errors.push('Fase 8 incompleta: '+token);if(!fs.existsSync(path.join(root,'js/music-tools.js')))errors.push('Fase 8 JS ausente.');}
if(info.phase>=7){const page=fs.readFileSync(path.join(root,'modo-live.html'),'utf8');for(const token of ['live-scroll-toggle','scroll-speed','live-section-strip','section-repeat'])if(!page.includes(token))errors.push('Fase 7 incompleta: '+token);const live=fs.readFileSync(path.join(root,'js/live-mode.js'),'utf8');for(const token of ['requestAnimationFrame','goSection','repeatSection','updateProgress'])if(!live.includes(token))errors.push('Fase 7 JS incompleto: '+token);}
if(info.phase>=11){const page=fs.readFileSync(path.join(root,'configuracoes.html'),'utf8');for(const token of ['data-cloud-upload','data-cloud-download','data-cloud-auto-sync','js/cloud-sync.js','js/settings.js'])if(!page.includes(token))errors.push('Fase 11 incompleta: '+token);for(const required of ['js/cloud-sync.js','js/settings.js','css/settings.css'])if(!fs.existsSync(path.join(root,required)))errors.push('Fase 11 arquivo ausente: '+required);}
if(info.phase>=12){const page=fs.readFileSync(path.join(root,'equipes.html'),'utf8');for(const token of ['team-list','member-list','permission-summary','js/teams.js','css/teams.css'])if(!page.includes(token))errors.push('Fase 12 incompleta: '+token);for(const required of ['equipes.html','js/teams.js','css/teams.css'])if(!fs.existsSync(path.join(root,required)))errors.push('Fase 12 arquivo ausente: '+required);const setlists=fs.readFileSync(path.join(root,'minhas-listas.html'),'utf8');if(!setlists.includes('setlist-team'))errors.push('Fase 12: associação equipe/repertório ausente.');}
if(info.phase>=13){const page=fs.readFileSync(path.join(root,'sala-live.html'),'utf8');for(const token of ['create-room-btn','join-room-btn','director-next','room-member-list','js/live-room.js'])if(!page.includes(token))errors.push('Fase 13 incompleta: '+token);for(const required of ['sala-live.html','js/live-room.js','js/live-room-client.js','css/live-room.css'])if(!fs.existsSync(path.join(root,required)))errors.push('Fase 13 arquivo ausente: '+required);const live=fs.readFileSync(path.join(root,'modo-live.html'),'utf8');if(!live.includes('js/live-room-client.js'))errors.push('Fase 13: cliente da Sala Live ausente no Modo Live.');}
if(info.phase>=14){const page=fs.readFileSync(path.join(root,'sala-live.html'),'utf8');for(const token of ['worship-flow-panel','flow-section-select','flow-dynamics','flow-modulation','data-flow-action'])if(!page.includes(token))errors.push('Fase 14 incompleta: '+token);const roomJs=fs.readFileSync(path.join(root,'js/live-room.js'),'utf8');for(const token of ['applyFlow','flow.history','extractSections'])if(!roomJs.includes(token))errors.push('Fase 14 JS incompleto: '+token);const client=fs.readFileSync(path.join(root,'js/live-room-client.js'),'utf8');for(const token of ['live-worship-flow','gotoSection','applyFlow'])if(!client.includes(token))errors.push('Fase 14 client incompleto: '+token);}
if(info.phase>=15){const page=fs.readFileSync(path.join(root,'modo-live.html'),'utf8');for(const token of ['external-controls-dialog','external-controls-open','js/external-controls.js','css/external-controls.css'])if(!page.includes(token))errors.push('Fase 15 incompleta: '+token);for(const required of ['js/external-controls.js','css/external-controls.css'])if(!fs.existsSync(path.join(root,required)))errors.push('Fase 15 arquivo ausente: '+required);const controls=fs.readFileSync(path.join(root,'js/external-controls.js'),'utf8');for(const token of ['requestMIDIAccess','data-learn-action','StageMusicExternalControls','stopImmediatePropagation'])if(!controls.includes(token))errors.push('Fase 15 JS incompleto: '+token);}
if(info.phase>=16){const page=fs.readFileSync(path.join(root,'eventos.html'),'utf8');for(const token of ['event-list','event-members','event-checklist','js/events.js','css/events.css'])if(!page.includes(token))errors.push('Fase 16 incompleta: '+token);for(const required of ['eventos.html','js/events.js','css/events.css'])if(!fs.existsSync(path.join(root,required)))errors.push('Fase 16 arquivo ausente: '+required);}
if(errors.length){console.error('AUDITORIA REPROVADA\n'+errors.join('\n'));process.exit(1)}console.log(`AUDITORIA APROVADA — ${info.app} ${info.version} | ${htmls.length} páginas | ${info.date} ${info.time}`);if(warnings.length)console.warn(warnings.join('\n'));

